### ISSUE TITLE
Compile issue with "Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error"

### ISSUE THREAD

**Issue by zhaocheng3326** [Nanguage/bioView#2]
Hi there,

It looks like the nim with version of (0.19, 0.20, 1.0.4) has the compiling issue when running the test.sh.

The error message is "
Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error
"
Any clues to solve this problem will be appreciated.
Thanks.

**Comment by Nanguage** [comment]
It's caused by nim's update about nil state for string/seqs in 0.19.0. I have fixed this temporarily by add --nilseqs:on compile option, see the commit: https://github.com/Nanguage/bioView/commit/9acc9c7b631fcb853a7d4f09f02f865c2031db02

**Comment by zhaocheng3326** [comment]
@Nanguage  Great! And the problem solved.  Thank you very much. What a shiny tool it is!
